project:
  type: book
  output-dir: docs

book:
  title: "BS3008: Computer Aided Drug Discovery"
  author: "Kevin Fo"
  chapters:
    - index.qmd
    - part: "**PART 1 : LECTURES**"
      chapters:
        - intro.qmd
        - wk2.qmd
        - summary.qmd
  sharing: [twitter, facebook]
  page-navigation: true
  repo-url: https://github.com/kevfo/BS3008-Notes
  repo-actions: [edit, issue]

bibliography: references.bib

format:
  html:
    toc: true 
    theme:
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual
