project:
  type: book
  output-dir: docs

book:
  title: "BS3008: Computer Aided Drug Discovery"
  author: "Kevin Fo"
  chapters:
    - index.qmd
    - part: "**PART 1 : LECTURES**"
      chapters:
        - intro.qmd
        - wk2a.qmd
        - wk3.qmd
        - wk2.qmd
        - wk5.qmd
        - wk6.qmd
        - wk7.qmd
        - wk8.qmd
        - wk9.qmd
    - part: "**PART 2 : PRACTICAL SESSIONS**"
      chapters:
        - lab1.qmd
        - P2.qmd
        - P3.qmd
  sharing: [twitter, facebook]
  page-navigation: true
  repo-url: https://github.com/kevfo/BS3008-Notes
  repo-actions: [edit, issue]
  reader-mode: true
  comments: 
    hypothesis: true

bibliography: references.bib

format:
  html:
    toc: true 
    theme:
      light: cosmo
      dark: darkly

editor: visual
